---
- name: restart kube-proxy
  service:
    name: kube-proxy
    state: restarted
  become: yes

- name: restart kubelet
  service:
    name: kubelet
    state: restarted
  become: yes

- name: restart flanneld
  service:
    name: flanneld
    state: restarted
  become: yes
